extends Node

export (String) var csv_file_path = "res://Axl_mod/Localization/translations2.csv"
export (String) var translation_directory_path = "res://Axl_mod/Localization/"

var translation_keys = [
	
	"TOTAL_TIME", 
	
	
	"DISCLAIMER1", 
	"MADE_BY", 
	"INSPIRED_BY", 
	"SPECIALTHANKSTEXT", 
	"16-BIT_TITLE", 
	"OPTIONS_START", 
	"KEYCFG_START", 
	"LEADERBOARDS", 
	"GAME_START", 
	"GAME_START_X", 
	"GAME_START_AXL", 
	"GAME_START_ZERO", 
	
	
	"ON_VALUE", 
	"OFF_VALUE", 
	"EXIT_BUTTON", 
	
	
	"ARMORSETUP_TITLE", 
	"LOADOUT_DISC", 
	
	
	"DEFAULTHEAD_NAME", 
	"DEFAULTHEAD_DISC", 
	"DEFAULTBODY_NAME", 
	"DEFAULTBODY_DISC", 
	"DEFAULTARMS_NAME", 
	"DEFAULTARMS_DISC", 
	"DEFAULTLEGS_NAME", 
	"DEFAULTLEGS_DISC", 
	
	"HERMESHEAD_NAME", 
	"HERMESHEAD_DISC", 
	"HERMESBODY_NAME", 
	"HERMESBODY_DISC", 
	"HERMESARMS_NAME", 
	"HERMESARMS_DISC", 
	"HERMESLEGS_NAME", 
	"HERMESLEGS_DISC", 
	
	"ICARUSHEAD_NAME", 
	"ICARUSHEAD_DISC", 
	"ICARUSBODY_NAME", 
	"ICARUSBODY_DISC", 
	"ICARUSARMS_NAME", 
	"ICARUSARMS_DISC", 
	"ICARUSLEGS_NAME", 
	"ICARUSLEGS_DISC", 
	
	
	"AXLNORMAL_NAME", 
	"AXLNORMAL_DISC", 
	"AXLWHITE_NAME", 
	"AXLWHITE_DISC", 
	
	
	"TANK_ABV", 
	"OPTIONS_ABV", 
	"KEYCFG_ABV", 
	"ACHIEV_ABV", 
	
	"X_WPNMENU", 
	"SUNFLOWER_WPNMENU", 
	"ANTONION_WPNMENU", 
	"MANTIS_WPNMENU", 
	"MANOWAR_WPNMENU", 
	"PANDA_WPNMENU", 
	"TRILOBYTE_WPNMENU", 
	"YETI_WPNMENU", 
	"ROOSTER_WPNMENU", 
	
	"AXL_WPNMENU", 
	"SUNFLOWER_AXL_WPNMENU", 
	"ANTONION_AXL_WPNMENU", 
	"MANTIS_AXL_WPNMENU", 
	"MANOWAR_AXL_WPNMENU", 
	"PANDA_AXL_WPNMENU", 
	"TRILOBYTE_AXL_WPNMENU", 
	"YETI_AXL_WPNMENU", 
	"ROOSTER_AXL_WPNMENU", 
	
	"SUNFLOWER_ZERO_WPNMENU", 
	"ANTONION_ZERO_WPNMENU", 
	"MANTIS_ZERO_WPNMENU", 
	"MANOWAR_ZERO_WPNMENU", 
	"PANDA_ZERO_WPNMENU", 
	"TRILOBYTE_ZERO_WPNMENU", 
	"YETI_ZERO_WPNMENU", 
	"ROOSTER_ZERO_WPNMENU", 
	
	"SUNFLOWER_ZERO_DISC", 
	"ANTONION_ZERO_DISC", 
	"MANTIS_ZERO_DISC", 
	"MANOWAR_ZERO_DISC", 
	"PANDA_ZERO_DISC", 
	"TRILOBYTE_ZERO_DISC", 
	"YETI_ZERO_DISC", 
	"ROOSTER_ZERO_DISC", 
	
	"ZERO_WPNMENU", 
	"BFAN_WPNMENU", 
	"DGLAIVE_WPNMENU", 
	"TBREAKER_WPNMENU", 
	"KKNUCKLE_WPNMENU", 
	"VHANGER_WPNMENU", 
	"SIGMABLADE_WPNMENU", 
	
	
	"YOUGOT_TITLE", 
	"SUNFLOWER_WEAPON", 
	"ANTONION_WEAPON", 
	"MANTIS_WEAPON", 
	"MANOWAR_WEAPON", 
	"PANDA_WEAPON", 
	"TRILOBYTE_WEAPON", 
	"YETI_WEAPON", 
	"ROOSTER_WEAPON", 
	
	
	"OPTIONS_TITLE", 
	"LANGUAGE_OPTION", 
	"REMIX_OPTION", 
	"DT_DASH_OPTION", 
	"SKIP_DIAG_OPTION", 
	"CHARGE_OPTION", 
	"ACHIEV_OPTION", 
	"MUSIC_OPTION", 
	"SOUND_OPTION", 
	"VSync", 
	"FPS_OPTION", 
	"WSIZE_OPTION", 
	"FULLSCREEN_OPTION", 
	"CRT_OPTION", 
	"DEBUG_OPTION", 
	"SHOWIGT_OPTION", 
	"GATEWAYSKIP_OPTION", 
	"CLEARSAVE_OPTION", 
	"CLEARSAVE_CONFIRM", 
	"RESET_ACHIEV", 
	"CLEARSAVE_CONFIRM", 
	"RESET_ACHIEV_FINISHED", 
	
	"ASPECT_OPTION", 
	"IGNORE_VALUE", 
	"KEEP_VALUE", 
	
	
	"KEYCFG_TITLE", 
	"ACTION_CTG", 
	"KEYBOARD_CTG", 
	"JOYPAD_CTG", 
	"LEFT_ACT", 
	"RIGHT_ACT", 
	"UP_ACT", 
	"DOWN_ACT", 
	"SHOT_ACT", 
	"SHOT2_ACT", 
	"JUMP_ACT", 
	"DASH_ACT", 
	"ARMORABILITY_ACT", 
	"PREV_ACT", 
	"NEXT_ACT", 
	"PAUSE_ACT", 
	"CONFIRM_ACT", 
	"WPNLEFT_ACT", 
	"WPNRIGHT_ACT", 
	"WPNUP_ACT", 
	"WPNDOWN_ACT", 
	"WPNRESET_ACT", 
	
	
	"ACHIEV_SCREEN_TITLE", 
	"ACHIEVEMENTSUNLOCKED", 
	"DEBUGACHIEVTITLE", 
	"DEBUGACHIEVDISC", 
	
	"BEATINTRO_DISC", 
	"BEATINTRO_TITLE", 
	"COLLECTALLHEARTS_DISC", 
	"COLLECTALLHEARTS_TITLE", 
	"COLLECTALLSUBTANKS_DISC", 
	"COLLECTALLSUBTANKS_TITLE", 
	"COLLECTFULLHERMES_DISC", 
	"COLLECTFULLHERMES_TITLE", 
	"COLLECTFULLICARUS_DISC", 
	"COLLECTFULLICARUS_TITLE", 
	"SURFEDONMISSILE_DISC", 
	"SURFEDONMISSILE_TITLE", 
	
	"DEFEATEDALL_DISC", 
	"DEFEATEDALL_TITLE", 
	"DEFEATEDANY_DISC", 
	"DEFEATEDANY_TITLE", 
	"GIGACRUSHKILL_DISC", 
	"GIGACRUSHKILL_TITLE", 
	"PELEDOSGAMES_DISC", 
	"PELEDOSGAMES_TITLE", 
	"PERFECTKILL_DISC", 
	"PERFECTKILL_TITLE", 
	"XDRIVEDODGE_DISC", 
	"XDRIVEDODGE_TITLE", 
	"GIGACRUSHKILL_DISC", 
	"GIGACRUSHKILL_TITLE", 
	
	"ANTONIONBUSTERONLY_DISC", 
	"ANTONIONBUSTERONLY_TITLE", 
	"ANTONIONNAKED_DISC", 
	"ANTONIONNAKED_TITLE", 
	"ANTONIONNODAMAGE_DISC", 
	"ANTONIONNODAMAGE_TITLE", 
	"ANTONIONNOROTATION_DISC", 
	"ANTONIONNOROTATION_TITLE", 
	
	"MANOWARBUSTERONLY_DISC", 
	"MANOWARBUSTERONLY_TITLE", 
	"MANOWARNAKED_DISC", 
	"MANOWARNAKED_TITLE", 
	"MANOWARNODAMAGE_DISC", 
	"MANOWARNODAMAGE_TITLE", 
	"MANOWARDOOREXPLODED_DISC", 
	"MANOWARDOOREXPLODED_TITLE", 
	
	"MANTISBUSTERONLY_DISC", 
	"MANTISBUSTERONLY_TITLE", 
	"MANTISNAKED_DISC", 
	"MANTISNAKED_TITLE", 
	"MANTISNODAMAGE_DISC", 
	"MANTISNODAMAGE_TITLE", 
	"MANTISLIT_DISC", 
	"MANTISLIT_TITLE", 
	"MANTISUNDETECTED_DISC", 
	"MANTISUNDETECTED_TITLE", 
	
	"PANDABUSTERONLY_DISC", 
	"PANDABUSTERONLY_TITLE", 
	"PANDANAKED_DISC", 
	"PANDANAKED_TITLE", 
	"PANDANODAMAGE_DISC", 
	"PANDANODAMAGE_TITLE", 
	"PANDARIDEREACHED_DISC", 
	"PANDARIDEREACHED_TITLE", 
	
	"ROOSTERBUSTERONLY_DISC", 
	"ROOSTERBUSTERONLY_TITLE", 
	"ROOSTERNAKED_DISC", 
	"ROOSTERNAKED_TITLE", 
	"ROOSTERNODAMAGE_DISC", 
	"ROOSTERNODAMAGE_TITLE", 
	"ROOSTERFROZEN_DISC", 
	"ROOSTERFROZEN_TITLE", 
	
	"SUNFLOWERBUSTERONLY_DISC", 
	"SUNFLOWERBUSTERONLY_TITLE", 
	"SUNFLOWERNAKED_DISC", 
	"SUNFLOWERNAKED_TITLE", 
	"SUNFLOWERNODAMAGE_DISC", 
	"SUNFLOWERNODAMAGE_TITLE", 
	"SUNFLOWERGOTSSSRANK_DISC", 
	"SUNFLOWERGOTSSSRANK_TITLE", 
	
	"TRILOBYTEBUSTERONLY_DISC", 
	"TRILOBYTEBUSTERONLY_TITLE", 
	"TRILOBYTENAKED_DISC", 
	"TRILOBYTENAKED_TITLE", 
	"TRILOBYTENODAMAGE_DISC", 
	"TRILOBYTENODAMAGE_TITLE", 
	
	"YETIBUSTERONLY_DISC", 
	"YETIBUSTERONLY_TITLE", 
	"YETINAKED_DISC", 
	"YETINAKED_TITLE", 
	"YETINODAMAGE_DISC", 
	"YETINODAMAGE_TITLE", 
	"YETIDOOREXPLODED_DISC", 
	"YETIDOOREXPLODED_TITLE", 
	
	"VILEJAKOBBUSTERONLY_DISC", 
	"VILEJAKOBBUSTERONLY_TITLE", 
	"VILEJAKOBNAKED_DISC", 
	"VILEJAKOBNAKED_TITLE", 
	"VILEJAKOBNODAMAGE_DISC", 
	"VILEJAKOBNODAMAGE_TITLE", 
	"VILEDEFEATEDTWICE_DISC", 
	"VILEDEFEATEDTWICE_TITLE", 
	"VILEDEVILBEARDEFEATED_DISC", 
	"VILEDEVILBEARDEFEATED_TITLE", 
	"VILEJAKOBDEFEATED_DISC", 
	"VILEJAKOBDEFEATED_TITLE", 
	"VILESIGMADEFEATED_DISC", 
	"VILESIGMADEFEATED_TITLE", 
	
	"GATEWAYFIESTA_DISC", 
	"GATEWAYFIESTA_TITLE", 
	
	"COPYBUSTERONLY_DISC", 
	"COPYBUSTERONLY_TITLE", 
	"COPYNAKED_DISC", 
	"COPYNAKED_TITLE", 
	"COPYNODAMAGE_DISC", 
	"COPYNODAMAGE_TITLE", 
	"COPYDEFEATED_DISC", 
	"COPYDEFEATED_TITLE", 
	
	"SIGMANAKED_DISC", 
	"SIGMANAKED_TITLE", 
	"SIGMANODAMAGE_DISC", 
	"SIGMANODAMAGE_TITLE", 
	
	"LUMINENAKED_DISC", 
	"LUMINENAKED_TITLE", 
	"LUMINENODAMAGE_DISC", 
	"LUMINENODAMAGE_TITLE", 
	"SERAPHNAKED_DISC", 
	"SERAPHNAKED_TITLE", 
	"SERAPHNODAMAGE_DISC", 
	"SERAPHNODAMAGE_TITLE", 
	"SERAPHDEFEATED_DISC", 
	"SERAPHDEFEATED_TITLE", 
	
	"SECRET1DEFEATED_DISC", 
	"SECRET1DEFEATED_TITLE", 
	"SECRET2DEFEATED_DISC", 
	"SECRET2DEFEATED_TITLE", 
	"SECRET3DEFEATED_DISC", 
	"SECRET3DEFEATED_TITLE", 
	
	
	"COLLECTBLACKZERO_TITLE", 
	"COLLECTBLACKZERO_DISC", 
	
	
	"STAGE_DC", 
	"BOSS_DC", 
	"COMPLETION_DC", 
	"NOAHSPARK_STAGE", 
	"NOAHSPARK_NAME", 
	"SUNFLOWER_STAGE", 
	"SUNFLOWER_NAME", 
	"ANTONION_STAGE", 
	"ANTONION_NAME", 
	"MANTIS_STAGE", 
	"MANTIS_NAME", 
	"MANOWAR_STAGE", 
	"MANOWAR_NAME", 
	"PANDA_STAGE", 
	"PANDA_NAME", 
	"TRILOBYTE_STAGE", 
	"TRILOBYTE_NAME", 
	"YETI_STAGE", 
	"YETI_NAME", 
	"ROOSTER_STAGE", 
	"ROOSTER_NAME", 
	"JAKOB_STAGE", 
	"GATEWAY_STAGE", 
	"SIGMA_STAGE", 
	
	
	
	
	"HERMESHEAD1", 
	"HERMESHEAD2", 
	"HERMESHEAD3", 
	"HERMESHEAD4", 
	
	"HERMESBODY1", 
	"HERMESBODY2", 
	"HERMESBODY3", 
	"HERMESBODY4", 
	
	"HERMESARMS1", 
	"HERMESARMS2", 
	"HERMESARMS3", 
	"HERMESARMS4", 
	"HERMESARMS5", 
	
	"HERMESLEGS1", 
	"HERMESLEGS2", 
	"HERMESLEGS3", 
	"HERMESLEGS4", 
	
	
	"ICARUSHEAD1", 
	"ICARUSHEAD2", 
	"ICARUSHEAD3", 
	"ICARUSHEAD4", 
	
	"ICARUSBODY1", 
	"ICARUSBODY2", 
	"ICARUSBODY3", 
	"ICARUSBODY4", 
	
	"ICARUSARMS1", 
	"ICARUSARMS2", 
	"ICARUSARMS3", 
	"ICARUSARMS4", 
	"ICARUSARMS5", 
	
	"ICARUSLEGS1", 
	"ICARUSLEGS2", 
	"ICARUSLEGS3", 
	"ICARUSLEGS4", 
	
	
	
	"INTRO2-1", 
	"INTRO2-2", 
	"INTRO2-3", 
	"INTRO2-4", 
	"INTRO2-5", 
	"INTRO2-6", 
	"INTRO2-7", 
	"INTRO2-8", 
	"INTRO2-9", 
	"INTRO2-10", 
	"INTRO2-11", 
	"INTRO2-12", 
	"INTRO2-13", 
	
	"INTRO3-1", 
	"INTRO3-2", 
	"INTRO3-3", 
	"INTRO3-4", 
	"INTRO3-5", 
	"INTRO3-6", 
	"INTRO3-7", 
	"INTRO3-8", 
	
	
	"ANTONION1", 
	"ANTONION2", 
	"ANTONION3", 
	"ANTONION4", 
	"ANTONION5", 
	"ANTONION6", 
	
	
	"MANOWAR1", 
	"MANOWAR2", 
	"MANOWAR3", 
	"MANOWAR4", 
	"MANOWAR5", 
	"MANOWAR6", 
	"MANOWAR7", 
	"MANOWAR8", 
	"MANOWAR9", 
	
	
	"MANTIS1", 
	"MANTIS2", 
	"MANTIS3", 
	"MANTIS4", 
	"MANTIS5", 
	"MANTIS6", 
	"MANTIS7", 
	"MANTIS8", 
	
	
	"PANDA1", 
	"PANDA2", 
	"PANDA3", 
	"PANDA4", 
	"PANDA5", 
	"PANDA6", 
	"PANDA7", 
	"PANDA8", 
	"PANDA9", 
	
	
	"ROOSTER1", 
	"ROOSTER2", 
	"ROOSTER3", 
	"ROOSTER4", 
	"ROOSTER5", 
	"ROOSTER6", 
	"ROOSTER7", 
	"ROOSTER8", 
	"ROOSTER9", 
	
	
	"SUNFLOWER1", 
	"SUNFLOWER2", 
	"SUNFLOWER3", 
	"SUNFLOWER4", 
	"SUNFLOWER5", 
	"SUNFLOWER6", 
	
	
	"TRILOBYTE1", 
	"TRILOBYTE2", 
	"TRILOBYTE3", 
	"TRILOBYTE4", 
	
	
	"YETI1", 
	"YETI2", 
	"YETI3", 
	"YETI4", 
	"YETI5", 
	"YETI6", 
	"YETI7", 
	
	
	"VILE1-1", 
	"VILE1-2", 
	"VILE1-3", 
	"VILE1-4", 
	"VILE1-5", 
	"VILE1-6", 
	"VILE1-7", 
	"VILE1-8", 
	"VILE1-9", 
	
	"VILE2-1", 
	"VILE2-2", 
	"VILE2-3", 
	"VILE2-4", 
	"VILE2-5", 
	"VILE2-6", 
	
	"VILE3-1", 
	"VILE3-2", 
	"VILE3-3", 
	"VILE3-4", 
	"VILE3-5", 
	"VILE3-6", 
	"VILE3-7", 
	
	"VILE4-1", 
	"VILE4-2", 
	"VILE4-3", 
	"VILE4-4", 
	"VILE4-5", 
	"VILE4-6", 
	
	
	"COPYSIGMA1", 
	"COPYSIGMA2", 
	"COPYSIGMA3", 
	"COPYSIGMA4", 
	"COPYSIGMA5", 
	"COPYSIGMA6", 
	"COPYSIGMA7", 
	
	
	"SIGMA1", 
	"SIGMA2", 
	"SIGMA3", 
	"SIGMA4", 
	"SIGMA5", 
	"SIGMA6", 
	"SIGMA7", 
	"SIGMA8", 
	"SIGMA9", 
	"SIGMA10", 
	"SIGMA11", 
	"SIGMA12", 
	"SIGMA13", 
	
	
	"FINALLUMINE1", 
	"FINALLUMINE2", 
	"FINALLUMINE3", 
	"FINALLUMINE4", 
	"FINALLUMINE5", 
	"FINALLUMINE6", 
	"FINALLUMINE7", 
	"FINALLUMINE8", 
	"FINALLUMINE9", 
	"FINALLUMINE10", 
	"FINALLUMINE11", 
	"FINALLUMINE12", 
	"FINALLUMINE13", 
	"FINALLUMINE14", 
	"FINALLUMINE15", 
	"FINALLUMINE16", 
	"FINALLUMINE17", 
	"FINALLUMINE18", 
	"FINALLUMINE19", 
	"FINALLUMINE20", 
	"FINALLUMINE21", 
	"FINALLUMINE22", 
	"FINALLUMINE23", 
	"FINALLUMINE24", 
	"FINALLUMINE25", 
	"FINALLUMINE26", 
	"FINALLUMINE27", 
	"FINALLUMINE28", 
	"FINALLUMINE29", 
	"FINALLUMINE30", 
	"FINALLUMINE31", 
	"FINALLUMINE32", 
	"FINALLUMINE33", 
	"FINALLUMINE34", 
	"FINALLUMINE35", 
	"FINALLUMINE36", 
	"FINALLUMINE37", 
	"FINALLUMINE38", 
	"FINALLUMINE39", 
	"FINALLUMINE40", 
	
	
	"ENDING1-1", 
	"ENDING1-2", 
	"ENDING1-3", 
	"ENDING1-4", 
	"ENDING1-5", 
	"ENDING1-6", 
	"ENDING1-7", 
	
	
	"ENDING2-1", 
	"ENDING2-2", 
	"ENDING2-3", 
	"ENDING2-4", 
	
	
	"FINAL-1", 
	"FINAL-2", 
	"FINAL-3", 
	"FINAL-4", 
	"FINAL-5", 
	
	
	"FINAL2-1", 
	"FINAL2-2", 
	"FINAL2-3", 
	"FINAL2-4", 
	"FINAL2-5", 
	
	
	"FINAL3-1", 
	"FINAL3-2", 
	"FINAL3-3", 
	"FINAL3-4", 
	"FINAL3-5", 
	"FINAL3-6", 
	"FINAL3-7", 
	
	
	"SECRET2-1", 
	"SECRET2-2", 
	"SECRET2-3", 
	"SECRET2-4", 
	"SECRET2-5", 
	"SECRET2-6", 
	"SECRET2-7", 
	"SECRET2-8", 
	"SECRET2-9", 
	"SECRET2-10", 
	"SECRET2-11", 
	"SECRET2-12", 
	"SECRET2-13", 
	
	"SECRET2-14", 
	"SECRET2-15", 
	"SECRET2-16", 
	"SECRET2-17", 
	"SECRET2-18", 
	"SECRET2-19", 
	
	
	"SECRET3-1", 
	"SECRET3-2", 
	"SECRET3-3", 
	"SECRET3-4", 
	"SECRET3-5", 
	"SECRET3-6", 
	"SECRET3-7", 
	
	"SECRET3-8", 
	
	
	"ZEROSECRET1", 
	"ZEROSECRET2", 
	"ZEROSECRET3", 
	"ZEROSECRET4", 
	"ZEROSECRET5", 
	"ZEROSECRET6", 
	"ZEROSECRET7", 
	"ZEROSECRET8", 
	"ZEROSECRET9", 
	"ZEROSECRET10", 
	"ZEROSECRET11", 
	"ZEROSECRET12", 
	"ZEROSECRET13", 
	"ZEROSECRET14", 
	"ZEROSECRET15", 
	"ZEROSECRET16", 
	
	
	
	"INTRO2-1_AXL", 
	"INTRO2-2_AXL", 
	"INTRO2-3_AXL", 
	"INTRO2-4_AXL", 
	"INTRO2-5_AXL", 
	"INTRO2-6_AXL", 
	"INTRO2-7_AXL", 
	"INTRO2-8_AXL", 
	"INTRO2-9_AXL", 
	"INTRO2-10_AXL", 
	"INTRO2-11_AXL", 
	"INTRO2-12_AXL", 
	"INTRO2-13_AXL", 
	
	"INTRO3-1_AXL", 
	"INTRO3-2_AXL", 
	"INTRO3-3_AXL", 
	"INTRO3-4_AXL", 
	"INTRO3-5_AXL", 
	"INTRO3-6_AXL", 
	"INTRO3-7_AXL", 
	"INTRO3-8_AXL", 
	"INTRO3-9_AXL", 
	"INTRO3-10_AXL", 
	"INTRO3-11_AXL", 
	
	
	"ANTONION1_AXL", 
	"ANTONION2_AXL", 
	"ANTONION3_AXL", 
	"ANTONION4_AXL", 
	"ANTONION5_AXL", 
	"ANTONION6_AXL", 
	
	
	"MANOWAR1_AXL", 
	"MANOWAR2_AXL", 
	"MANOWAR3_AXL", 
	"MANOWAR4_AXL", 
	"MANOWAR5_AXL", 
	"MANOWAR6_AXL", 
	"MANOWAR7_AXL", 
	
	
	"MANTIS1_AXL", 
	"MANTIS2_AXL", 
	"MANTIS3_AXL", 
	"MANTIS4_AXL", 
	"MANTIS5_AXL", 
	"MANTIS6_AXL", 
	"MANTIS7_AXL", 
	"MANTIS8_AXL", 
	"MANTIS9_AXL", 
	
	
	"PANDA1_AXL", 
	"PANDA2_AXL", 
	"PANDA3_AXL", 
	"PANDA4_AXL", 
	"PANDA5_AXL", 
	
	
	"ROOSTER1_AXL", 
	"ROOSTER2_AXL", 
	"ROOSTER3_AXL", 
	"ROOSTER4_AXL", 
	"ROOSTER5_AXL", 
	"ROOSTER6_AXL", 
	"ROOSTER7_AXL", 
	"ROOSTER8_AXL", 
	"ROOSTER9_AXL", 
	
	
	"SUNFLOWER1_AXL", 
	"SUNFLOWER2_AXL", 
	"SUNFLOWER3_AXL", 
	"SUNFLOWER4_AXL", 
	"SUNFLOWER5_AXL", 
	"SUNFLOWER6_AXL", 
	
	
	"TRILOBYTE1_AXL", 
	"TRILOBYTE2_AXL", 
	"TRILOBYTE3_AXL", 
	"TRILOBYTE4_AXL", 
	"TRILOBYTE5_AXL", 
	"TRILOBYTE6_AXL", 
	
	
	"YETI1_AXL", 
	"YETI2_AXL", 
	"YETI3_AXL", 
	"YETI4_AXL", 
	
	
	"VILE1-1_AXL", 
	"VILE1-2_AXL", 
	"VILE1-3_AXL", 
	"VILE1-4_AXL", 
	"VILE1-5_AXL", 
	
	"VILE2-1_AXL", 
	"VILE2-2_AXL", 
	"VILE2-3_AXL", 
	"VILE2-4_AXL", 
	"VILE2-5_AXL", 
	"VILE2-6_AXL", 
	"VILE2-7_AXL", 
	
	"VILE3-1_AXL", 
	"VILE3-2_AXL", 
	"VILE3-3_AXL", 
	"VILE3-4_AXL", 
	"VILE3-5_AXL", 
	"VILE3-6_AXL", 
	"VILE3-7_AXL", 
	"VILE3-8_AXL", 
	
	"VILE4-1_AXL", 
	"VILE4-2_AXL", 
	"VILE4-3_AXL", 
	"VILE4-4_AXL", 
	"VILE4-5_AXL", 
	
	
	"COPYSIGMA1_AXL", 
	"COPYSIGMA2_AXL", 
	"COPYSIGMA3_AXL", 
	"COPYSIGMA4_AXL", 
	"COPYSIGMA5_AXL", 
	"COPYSIGMA6_AXL", 
	"COPYSIGMA7_AXL", 
	
	
	"SIGMA1_AXL", 
	"SIGMA2_AXL", 
	"SIGMA3_AXL", 
	"SIGMA4_AXL", 
	"SIGMA5_AXL", 
	"SIGMA6_AXL", 
	"SIGMA7_AXL", 
	"SIGMA8_AXL", 
	"SIGMA9_AXL", 
	"SIGMA10_AXL", 
	"SIGMA11_AXL", 
	"SIGMA12_AXL", 
	"SIGMA13_AXL", 
	"SIGMA14_AXL", 
	
	
	"FINALLUMINE1_AXL", 
	"FINALLUMINE2_AXL", 
	"FINALLUMINE3_AXL", 
	"FINALLUMINE4_AXL", 
	"FINALLUMINE5_AXL", 
	"FINALLUMINE6_AXL", 
	"FINALLUMINE7_AXL", 
	"FINALLUMINE8_AXL", 
	"FINALLUMINE9_AXL", 
	"FINALLUMINE10_AXL", 
	"FINALLUMINE11_AXL", 
	"FINALLUMINE12_AXL", 
	"FINALLUMINE13_AXL", 
	"FINALLUMINE14_AXL", 
	"FINALLUMINE15_AXL", 
	"FINALLUMINE16_AXL", 
	"FINALLUMINE17_AXL", 
	"FINALLUMINE18_AXL", 
	"FINALLUMINE19_AXL", 
	"FINALLUMINE20_AXL", 
	"FINALLUMINE21_AXL", 
	"FINALLUMINE22_AXL", 
	"FINALLUMINE23_AXL", 
	"FINALLUMINE24_AXL", 
	"FINALLUMINE25_AXL", 
	"FINALLUMINE26_AXL", 
	"FINALLUMINE27_AXL", 
	"FINALLUMINE28_AXL", 
	"FINALLUMINE29_AXL", 
	"FINALLUMINE30_AXL", 
	"FINALLUMINE31_AXL", 
	"FINALLUMINE32_AXL", 
	"FINALLUMINE33_AXL", 
	
	
	"ENDING1-1_AXL", 
	"ENDING1-2_AXL", 
	"ENDING1-3_AXL", 
	"ENDING1-4_AXL", 
	"ENDING1-5_AXL", 
	"ENDING1-6_AXL", 
	"ENDING1-7_AXL", 
	
	
	"ENDING2-1_AXL", 
	"ENDING2-2_AXL", 
	"ENDING2-3_AXL", 
	"ENDING2-4_AXL", 
	"ENDING2-5_AXL", 
	
	
	"SECRET2-1_AXL", 
	"SECRET2-2_AXL", 
	"SECRET2-3_AXL", 
	"SECRET2-4_AXL", 
	"SECRET2-5_AXL", 
	"SECRET2-6_AXL", 
	"SECRET2-7_AXL", 
	"SECRET2-8_AXL", 
	"SECRET2-9_AXL", 
	"SECRET2-10_AXL", 
	"SECRET2-11_AXL", 
	"SECRET2-12_AXL", 
	"SECRET2-13_AXL", 
	
	"SECRET2-14_AXL", 
	"SECRET2-15_AXL", 
	"SECRET2-16_AXL", 
	"SECRET2-17_AXL", 
	"SECRET2-18_AXL", 
	"SECRET2-19_AXL", 
	"SECRET2-20_AXL", 
	"SECRET2-21_AXL", 
	"SECRET2-22_AXL", 
	"SECRET2-23_AXL", 
	"SECRET2-24_AXL", 
	"SECRET2-25_AXL", 
	"SECRET2-26_AXL", 
	
	
	"SECRET3-1_AXL", 
	"SECRET3-2_AXL", 
	"SECRET3-3_AXL", 
	"SECRET3-4_AXL", 
	"SECRET3-5_AXL", 
	"SECRET3-6_AXL", 
	"SECRET3-7_AXL", 
	"SECRET3-8_AXL", 
	"SECRET3-9_AXL", 
	"SECRET3-10_AXL", 
	
	"SECRET3-11_AXL", 
	"SECRET3-12_AXL", 
	"SECRET3-13_AXL", 
	"SECRET3-14_AXL", 
	"SECRET3-15_AXL", 
	"SECRET3-16_AXL", 
	
	
	
	"INTRO1-1_ZERO", 
	"INTRO1-2_ZERO", 
	"INTRO1-3_ZERO", 
	"INTRO1-4_ZERO", 
	"INTRO1-5_ZERO", 
	"INTRO1-6_ZERO", 
	
	"INTRO2-1_ZERO", 
	
	"INTRO2-2_ZERO", 
	"INTRO2-3_ZERO", 
	
	"INTRO2-4_ZERO", 
	"INTRO2-5_ZERO", 
	"INTRO2-6_ZERO", 
	"INTRO2-7_ZERO", 
	"INTRO2-8_ZERO", 
	"INTRO2-9_ZERO", 
	
	"INTRO3-1_ZERO", 
	"INTRO3-2_ZERO", 
	"INTRO3-3_ZERO", 
	"INTRO3-4_ZERO", 
	"INTRO3-5_ZERO", 
	"INTRO3-6_ZERO", 
	"INTRO3-7_ZERO", 
	"INTRO3-8_ZERO", 
	
	
	"ANTONION1_ZERO", 
	"ANTONION2_ZERO", 
	"ANTONION3_ZERO", 
	"ANTONION4_ZERO", 
	"ANTONION5_ZERO", 
	"ANTONION6_ZERO", 
	"ANTONION7_ZERO", 
	
	
	"MANOWAR1_ZERO", 
	"MANOWAR2_ZERO", 
	"MANOWAR3_ZERO", 
	"MANOWAR4_ZERO", 
	"MANOWAR5_ZERO", 
	"MANOWAR6_ZERO", 
	"MANOWAR7_ZERO", 
	"MANOWAR8_ZERO", 
	"MANOWAR9_ZERO", 
	"MANOWAR10_ZERO", 
	
	
	"MANTIS1_ZERO", 
	"MANTIS2_ZERO", 
	"MANTIS3_ZERO", 
	"MANTIS4_ZERO", 
	"MANTIS5_ZERO", 
	"MANTIS6_ZERO", 
	"MANTIS7_ZERO", 
	
	
	"PANDA1_ZERO", 
	"PANDA2_ZERO", 
	"PANDA3_ZERO", 
	"PANDA4_ZERO", 
	"PANDA5_ZERO", 
	"PANDA6_ZERO", 
	"PANDA7_ZERO", 
	"PANDA8_ZERO", 
	"PANDA9_ZERO", 
	
	
	"ROOSTER1_ZERO", 
	"ROOSTER2_ZERO", 
	"ROOSTER3_ZERO", 
	"ROOSTER4_ZERO", 
	"ROOSTER5_ZERO", 
	"ROOSTER6_ZERO", 
	"ROOSTER7_ZERO", 
	"ROOSTER8_ZERO", 
	"ROOSTER9_ZERO", 
	
	
	"SUNFLOWER1_ZERO", 
	"SUNFLOWER2_ZERO", 
	"SUNFLOWER3_ZERO", 
	"SUNFLOWER4_ZERO", 
	"SUNFLOWER5_ZERO", 
	"SUNFLOWER6_ZERO", 
	
	
	"TRILOBYTE1_ZERO", 
	"TRILOBYTE2_ZERO", 
	"TRILOBYTE3_ZERO", 
	"TRILOBYTE4_ZERO", 
	"TRILOBYTE5_ZERO", 
	"TRILOBYTE6_ZERO", 
	"TRILOBYTE7_ZERO", 
	
	
	"YETI1_ZERO", 
	"YETI2_ZERO", 
	"YETI3_ZERO", 
	"YETI4_ZERO", 
	"YETI5_ZERO", 
	
	
	"VILE1-1_ZERO", 
	"VILE1-2_ZERO", 
	"VILE1-3_ZERO", 
	"VILE1-4_ZERO", 
	"VILE1-5_ZERO", 
	"VILE1-6_ZERO", 
	"VILE1-7_ZERO", 
	
	"VILE2-1_ZERO", 
	"VILE2-2_ZERO", 
	"VILE2-3_ZERO", 
	"VILE2-4_ZERO", 
	"VILE2-5_ZERO", 
	"VILE2-6_ZERO", 
	
	"VILE3-1_ZERO", 
	"VILE3-2_ZERO", 
	"VILE3-3_ZERO", 
	"VILE3-4_ZERO", 
	"VILE3-5_ZERO", 
	"VILE3-6_ZERO", 
	"VILE3-7_ZERO", 
	
	"VILE4-1_ZERO", 
	"VILE4-2_ZERO", 
	"VILE4-3_ZERO", 
	"VILE4-4_ZERO", 
	"VILE4-5_ZERO", 
	"VILE4-6_ZERO", 
	
	
	"COPYSIGMA1_ZERO", 
	"COPYSIGMA2_ZERO", 
	"COPYSIGMA3_ZERO", 
	"COPYSIGMA4_ZERO", 
	"COPYSIGMA5_ZERO", 
	"COPYSIGMA6_ZERO", 
	"COPYSIGMA7_ZERO", 
	
	
	"SIGMA1_ZERO", 
	"SIGMA2_ZERO", 
	"SIGMA3_ZERO", 
	"SIGMA4_ZERO", 
	"SIGMA5_ZERO", 
	"SIGMA6_ZERO", 
	"SIGMA7_ZERO", 
	"SIGMA8_ZERO", 
	"SIGMA9_ZERO", 
	"SIGMA10_ZERO", 
	"SIGMA11_ZERO", 
	"SIGMA12_ZERO", 
	
	
	"FINALLUMINE1_ZERO", 
	"FINALLUMINE2_ZERO", 
	"FINALLUMINE3_ZERO", 
	"FINALLUMINE4_ZERO", 
	"FINALLUMINE5_ZERO", 
	"FINALLUMINE6_ZERO", 
	"FINALLUMINE7_ZERO", 
	"FINALLUMINE8_ZERO", 
	"FINALLUMINE9_ZERO", 
	"FINALLUMINE10_ZERO", 
	"FINALLUMINE11_ZERO", 
	"FINALLUMINE12_ZERO", 
	"FINALLUMINE13_ZERO", 
	"FINALLUMINE14_ZERO", 
	"FINALLUMINE15_ZERO", 
	"FINALLUMINE16_ZERO", 
	"FINALLUMINE17_ZERO", 
	"FINALLUMINE18_ZERO", 
	"FINALLUMINE19_ZERO", 
	"FINALLUMINE20_ZERO", 
	"FINALLUMINE21_ZERO", 
	"FINALLUMINE22_ZERO", 
	"FINALLUMINE23_ZERO", 
	"FINALLUMINE24_ZERO", 
	"FINALLUMINE25_ZERO", 
	"FINALLUMINE26_ZERO", 
	"FINALLUMINE27_ZERO", 
	"FINALLUMINE28_ZERO", 
	"FINALLUMINE29_ZERO", 
	"FINALLUMINE30_ZERO", 
	"FINALLUMINE31_ZERO", 
	"FINALLUMINE32_ZERO", 
	"FINALLUMINE33_ZERO", 
	"FINALLUMINE34_ZERO", 
	"FINALLUMINE35_ZERO", 
	"FINALLUMINE36_ZERO", 
	"FINALLUMINE37_ZERO", 
	"FINALLUMINE38_ZERO", 
	"FINALLUMINE39_ZERO", 
	"FINALLUMINE40_ZERO", 
	"FINALLUMINE41_ZERO", 
	
	
	"ENDING1-1_ZERO", 
	"ENDING1-2_ZERO", 
	"ENDING1-3_ZERO", 
	"ENDING1-4_ZERO", 
	"ENDING1-5_ZERO", 
	"ENDING1-6_ZERO", 
	"ENDING1-7_ZERO", 
	
	"ENDING2-1_ZERO", 
	"ENDING2-2_ZERO", 
	"ENDING2-3_ZERO", 
	"ENDING2-4_ZERO", 
	
	
	"SECRET2-1_ZERO", 
	"SECRET2-2_ZERO", 
	"SECRET2-3_ZERO", 
	"SECRET2-4_ZERO", 
	"SECRET2-5_ZERO", 
	"SECRET2-6_ZERO", 
	"SECRET2-7_ZERO", 
	"SECRET2-8_ZERO", 
	"SECRET2-9_ZERO", 
	"SECRET2-10_ZERO", 
	"SECRET2-11_ZERO", 
	"SECRET2-12_ZERO", 
	"SECRET2-13_ZERO", 
	"SECRET2-14_ZERO", 
	"SECRET2-15_ZERO", 
	"SECRET2-16_ZERO", 
	"SECRET2-17_ZERO", 
	"SECRET2-18_ZERO", 
	
	"SECRET2-19_ZERO", 
	"SECRET2-20_ZERO", 
	"SECRET2-21_ZERO", 
	"SECRET2-22_ZERO", 
	"SECRET2-23_ZERO", 
	"SECRET2-24_ZERO", 
	"SECRET2-25_ZERO", 
	"SECRET2-26_ZERO", 
	"SECRET2-27_ZERO", 
	"SECRET2-28_ZERO", 
	"SECRET2-29_ZERO", 
	
	
	"SECRET3-1_ZERO", 
	"SECRET3-2_ZERO", 
	"SECRET3-3_ZERO", 
	"SECRET3-4_ZERO", 
	"SECRET3-5_ZERO", 
	"SECRET3-6_ZERO", 
	"SECRET3-7_ZERO", 
	"SECRET3-8_ZERO", 
	"SECRET3-9_ZERO", 
	
	"SECRET3-10_ZERO", 
	"SECRET3-11_ZERO", 
	"SECRET3-12_ZERO", 
	"SECRET3-13_ZERO", 
	"SECRET3-14_ZERO", 
	"SECRET3-15_ZERO", 
]

func _ready() -> void :
	
	
	queue_free()

func export_all_translations_to_csv():
	var file = File.new()
	if file.open(csv_file_path, File.WRITE) != OK:
		print("Failed to open file for writing: " + csv_file_path)
		return

	var locales = TranslationServer.get_loaded_locales()
	var header = "key,en"
	for locale in locales:
		if locale != "en":
			header += "," + locale
	file.store_line(header)

	for key in translation_keys:
		var csv_line = "\"" + key + "\""
		
		TranslationServer.set_locale("en")
		var english_translation = tr(key)
		csv_line += ",\"" + english_translation + "\""
		
		for locale in locales:
			if locale != "en":
				TranslationServer.set_locale(locale)
				var translated_text = tr(key)
				csv_line += ",\"" + translated_text + "\""
		
		file.store_line(csv_line)

	file.close()
	print("Translations exported to CSV successfully for all locales")


func import_csv_as_translation():
	var file = File.new()
	if file.open(csv_file_path, File.READ) != OK:
		print("Failed to open CSV file")
		return
	
	var translations = {}
	
	var headers = file.get_csv_line()
	var locales = []
	
	for i in range(1, headers.size()):
		locales.append(headers[i])
	
	while not file.eof_reached():
		var line = file.get_csv_line()
		if line.size() == headers.size():
			var key = line[0]
			for i in range(1, line.size()):
				if not translations.has(locales[i - 1]):
					translations[locales[i - 1]] = {}
				translations[locales[i - 1]][key] = line[i]
	
	file.close()
	
	for locale in locales:
		var translation_file_path = translation_directory_path + "new." + locale + ".translation"
		file.open(translation_file_path, File.WRITE)
		file.store_line("[translation]")
		for key in translations[locale].keys():
			file.store_line("%s = %s" % [key, translations[locale][key]])
		file.close()
	
	print("Translations imported successfully")

